export const UPDATE_CONSTRUCTIONS_LIST = 'UPDATE_CONSTRUCTIONS_LIST'
export const UPDATE_SELECTION_CRITERIA = 'UPDATE_SELECTION_CRITERIA'
export const MARK_CONSTRUCTIONS_LIST_OBSOLETE = 'MARK_CONSTRUCTIONS_LIST_OBSOLETE'

export const INITIALIZE_APP_DATA = 'INITIALIZE_APP_DATA'

export const ADD_CONSTRUCTION = 'ADD_CONSTRUCTION'
export const UPDATE_CONSTRUCTION = 'UPDATE_CONSTRUCTION'
export const DELETE_CONSTRUCTION = 'DELETE_CONSTRUCTION'
